[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#575ECF"
backgroundColor = "#1B1B1B"
secondaryBackgroundColor = "#242424"
textColor = "#C5C1B9"
